[tool.poetry]
name = "scoutnet2airkey"
version = "0.0.0"
description = "Scoutnet EVVA Airkey integration"
authors = ["Jakob Schlyter <jakob@schlyter.se>"]
license = "BSD-2-Clause"
repository = "https://github.com/jschlyter/scoutnet2airkey"

[tool.poetry.dependencies]
python = "^3.9"
scoutnet = {git = "https://github.com/jschlyter/python-scoutnet.git", rev = "main"}
airkey = {git = "https://github.com/jschlyter/python-airkey.git", rev = "main"}
icecream = "^2.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scoutnet2airkey = "scoutnet2airkey:main"

[tool.pylama.linter.pycodestyle]
max_line_length = 132
ignore = "W606"

[tool.pylama.linter.mccabe]
complexity = 40
